mkdir CODIGO_FUENTE
cd CODIGO_FUENTE
echo TEXTO DE PRIMERA LINEA > README.txt
cd ..
mkdir DESPEGABLES
cd DESPEGABLES
echo TEXTO DE PRIMERA LINEA > README.txt
cd ..
mkdir DOCUMENTACION
cd DOCUMENTACION
echo TEXTO DE PRIMERA LINEA > README.txt
cd ..
mkdir EJECUTABLES
cd EJECUTABLES
echo TEXTO DE PRIMERA LINEA > README.txt
cd ..
mkdir SCRIPTS
cd SCRIPTS
echo TEXTO DE PRIMERA LINEA > README.txt
cd ..